Wait for current console.log tasks before exit
Otherwise, the following error may occur due to browser close:

/Users/sergey/corelibs-test-runner/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/sergey/corelibs-test-runner/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/Users/sergey/corelibs-test-runner/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/Users/sergey/corelibs-test-runner/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/sergey/corelibs-test-runner/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async Promise.all (index 0)